cc_library(
    name = "core",
    hdrs = [
        "util.h",
        "math.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "@com_google_absl//absl/status",
        "@com_google_absl//absl/strings:str_format",
    ],
)
