cc_library(
    name = "scene",
    srcs = [
        "gltf_loader.cc",
        "mesh.cc",
        "scene.cc",
    ],
    hdrs = [
        "gltf_loader.h",
        "mesh.h",
        "scene.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//lance/core",
        "//lance/rendering",
    ],
)
