cc_library(
    name = "scene",
    srcs = [
        "mesh.cc",
        "scene.cc",
    ],
    hdrs = [
        "mesh.h",
        "scene.h",
    ],
    visibility = ["//visibility:public"],
    deps = ["//lance/core"],
)
